### ISSUE TITLE
[BUG] 长图显示时模糊

### ISSUE THREAD

**Issue by duzhaokun123** [duzhaokun123/BilibiliHD#15]
### bug 表现
长图显示时模糊

### 重现步骤
动态找个长图然后查看大图

### 预期行为
清晰的图片

### 屏幕截图
![Screenshot_20210203-162837_bilibili_HD](https://user-images.githubusercontent.com/39830683/106719142-e91d1400-663c-11eb-94ba-361629f32a9c.png)

### Log
null

### 系统及应用信息
 - 设备: any
 - 系统: any
 - 应用版本: 至少有`0.1.4+b21d15f`
 - 应用构建类型: any

**Comment by duzhaokun123** [comment]
这应该是`StfalconImageViewer`的问题
`StfalconImageViewer`的缩放实现是`PhotoView`
很有可能是设置图片的缩放和方式有问题
把`PhotoView`找出来一改就行了

**Comment by duzhaokun123** [comment]
fixed

**Comment by China-ZhanChen** [comment]
如何登陆？


发送自 Windows 10 版邮件应用

发件人: 杜兆琨
发送时间: 2021年2月4日 17:58
收件人: duzhaokun123/BilibiliHD
抄送: Subscribed
主题: Re: [duzhaokun123/BilibiliHD] [BUG] 长图显示时模糊 (#15)

fixed

**Comment by duzhaokun123** [comment]
@China-ZhanChen 左侧菜单->设置->用户->右上加号->登录
用户名输手机号, 密码输密码
登不上看#12
此外请勿在一Issues问与主题无关的问题, 有问题请先搜索, 找不到再新开Issues
