### ISSUE TITLE
建议大佬稍微更改下动态页和视频播放页排版ヾ(•ω•`)o

### ISSUE THREAD

**Issue by Octomouch** [duzhaokun123/BilibiliHD#3]
转了一圈好像只有大佬在写HD版的安卓端，真是辛苦了😂，这边用安卓平板测试了下大佬的应用，确实比官方那个强制横屏就残疾的app好用很多，但是这边还是对一些小问题提出点小建议，如有打扰万分抱歉。
       首先是动态页排版，感觉两排交错非线性排列的方式有点杂乱，建议稍微修改下，如果能再增加一栏纯视频子选项就更好了；然后视频播放页的小窗上下分割的排列感觉不是很好看，如果能参照IPad端的那种布局就再好不过了。
       安卓板渴HD端良久，大佬能写真的万分感激o((>ω< ))o。

**Comment by duzhaokun123** [comment]
动态页面有考虑设计成可选的单列像web端那样

ipad端的视频布局长么样希望能提供一些截图

另外现在上学太累了, 暑假可能才能更新

**Comment by Octomouch** [comment]
![{47C1F683-129D-850A-BA03-77A71DA05C33}](https://user-images.githubusercontent.com/66351932/84592636-bf2e9b80-ae79-11ea-830d-4aac1dfcb22c.png)
大概就是这样。。。大佬辛苦了，不用急着更新，毕竟学业要紧😂

**Comment by Octomouch** [comment]
![Screenshot_20200614-172447_bilibili HD](https://user-images.githubusercontent.com/66351932/84593130-16823b00-ae7d-11ea-8010-2a45201a1d53.png)
然后现在平板上的显示效果大概是这样的，就感觉改一改比较好，还有就是暂时不支持4K清晰度

**Comment by Octomouch** [comment]
![Screenshot_20200614-172447_bilibili HD](https://user-images.githubusercontent.com/66351932/84593153-4d585100-ae7d-11ea-810d-3f1b1ad4afc0.png)
然后现在在板子上的显示效果大概是这样的，还有就是不支持4K显示

**Comment by zhouym233** [comment]
> ![Screenshot_20200614-172447_bilibili HD](https://user-images.githubusercontent.com/66351932/84593153-4d585100-ae7d-11ea-810d-3f1b1ad4afc0.png)
> 然后现在在板子上的显示效果大概是这样的，还有就是不支持4K显示

你的也是三星平板吗？我这边有出现弹幕字体过大的情况，不知在你的机器上如何？

**Comment by duzhaokun123** [comment]
@zhouym233 对于字体过大的问题以后会增加调整字体的选项的

@Octomouch 可能播放的就是4k视频只不过显示的不是

**Comment by Octomouch** [comment]
我是三星Tab S6，弹幕的话确实有点大，而且速度和透明度没有调节选项

**Comment by Octomouch** [comment]
还发现了几个动态页的bug😂，评论经常会错位，一个up的动态会在另一个up的名称下显示，不同类型动态(短视频，图片，视频发布)区分度不高容易混淆，而且没有评论转发显示T﹏T

**Comment by duzhaokun123** [comment]
@Octomouch 所以建议使用Web端看动态

我做这个现在主要是官方应用在我的平板电脑上无法联网

**Comment by Octomouch** [comment]
这样啊，官方应用不能联网就比较惨了，我这边的话，官方那个联网倒是没问题，就是横屏使用体验非常差劲。

**Comment by duzhaokun123** [comment]
@Octomouch 动态页现在使用 WebView 实现了, 与 Web 端相同

**Comment by Octomouch** [comment]
> @Octomouch 动态页现在使用 WebView 实现了, 与 Web 端相同

已经看到了，大佬辛苦了😂，但是WebView嵌套的直播好像不能播放，还有就是能不能增加下番剧播放的选项，明明是大会员但是不能看番剧也蛮苦恼的

**Comment by duzhaokun123** [comment]
抱歉 视频界面对我来说太难了
